### ISSUE TITLE
erb tags in comment lines should be ignored

### ISSUE THREAD

**Issue by github0013** [usabilityhub/rails-erb-loader#34]
I found rails-erb-loader evaluates anything in (.js|.jsx|etc..).erb, that is including comment lines.
https://github.com/rails/webpacker/issues/338

**Rails 5.1 initial application.js** has comment lines like this.
```js
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb
```

If you just add `.erb` to this application.js, `<%= javascript_pack_tag 'application' %>` is evaluated (without your intentions), and it gives error `undefined method javascript_pack_tag`.

I was thinking comment lines should be ignored to prevent unexpected errors like this.   Will it be possible?

**Comment by rhys-vdw** [comment]
Hi @github0013.

I see how this could be an unexpected gotcha!

Since ERB is language agnostic, I don't see this as a responsibility of an ERB compiler. Theoretically one might wish to generate comments with ERB (not sure why you would, but there's nothing about ERB that should know about JS or any other language that is being templated).

If this feature was to be added, it would have to implemented in `ERB` `erubis` or `erubi`, rather than this loader which simply provides an interface between webpack and these templating engines.

However, you can get around this by chaining [stripcomment-loader](https://www.npmjs.com/package/stripcomment-loader) before `rails-erb-loader`:

```js
// webpack.config.js

module.exports = {
    module: {
      rules: [
        {
          test: /\.js\.erb$/,
          enforce: 'pre',
          use: [
            'rails-erb-loader',
            'stripcomments-loader' // Loaders are supplied in reverse order.
          ]
        }
      ]
    }
  }
};
```

Note though that this change would also strip [configuration comments](https://github.com/usabilityhub/rails-erb-loader#dependencies) supported by `rails-erb-loader`, which you may wish to keep.

If you're very worried about this then you might want to add a custom ESLint rule that looks for instances of `<%` within a comment node and reports an error when they are found.

**Comment by github0013** [comment]
I was think it would be simple, but I guess it gets more complicated than just telling people not to put erb tags in comments.
since application.js has the erb tag, I feel like there will be a lot more people spend time on this `undefined method javascript_pack_tag`, then end up with posting issues on github and stackoverflow...

**Comment by rhys-vdw** [comment]
> Rails 5.1 initial application.js has comment lines like this

Yeah, interesting. Sorry, I missed that this was a script provided by Rails. I haven't checked, but I would assume, that Sprockets would also interpolate ERB in comments. Is this not the case?

Btw, you should avoid passing files through `rails-erb-loader` unless they actually contain ERB tags. A file called `application.js` should be filtered by the `test: /\.erb$/` attribute. I say this because every individual file processed by `rails-erb-loader` actually spawns a subprocess and starts an instance of Rails, which is not super fast.

**Comment by github0013** [comment]
like I explained in https://github.com/rails/webpacker/issues/338, I did add `.erb` to application.js

https://github.com/github0013/js_erb/commit/50a760cb1093d2f4b0199a050e01ce99c117539a

I am sure usually nobody would try to add erb tags and comment them in javascript files.  But in this case the initial application.js has a comment containing erb tag, so that's very easy to miss when you change it to `.js.erb`.
